package tablero2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author Alpe
 */
public class Ventanat2d extends javax.swing.JFrame {

    /**
     * Creates new form Ventanat2d
     */
    public Ventanat2d() {
        initComponents();
        JPanel panel = new JPanel();
        this.add(panel); //Añado el panel al JFrame
        panel.setPreferredSize(new Dimension(800, 600)); //Dimensiones del panel

        this.setTitle("Tablero 3 en raya");
        this.setSize(600, 500);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Función para dibujar el tablero y fichas del 3 en raya*/
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        // Establecer color y anchura de las lineas
        g2d.setColor(Color.ORANGE);
        g2d.setStroke(new BasicStroke(5));

        // Dibujar líneas horizontales del tablero
        g2d.drawLine(30, 70, 480, 70);
        g2d.drawLine(30, 200, 480, 200);
        g2d.drawLine(30, 330, 480, 330);
        g2d.drawLine(30, 460, 480, 460);

        // Dibujar líneas verticales del tablero
        g2d.drawLine(30, 70, 30, 460);
        g2d.drawLine(180, 70, 180, 460);
        g2d.drawLine(330, 70, 330, 460);
        g2d.drawLine(480, 70, 480, 460);

        // Establecer color y dibujar círculos rellenos y con bordes (fichas)
        g2d.setColor(Color.red);
        
        // relleno circulos fila1
        g2d.fillOval(58, 90, 95, 95);
        g2d.fillOval(208, 90, 95, 95);
        g2d.fillOval(358, 90, 95, 95);
        
        // relleno circulos fila2
        g2d.fillOval(58, 220, 95, 95);
        g2d.fillOval(208, 220, 95, 95);
        g2d.fillOval(358, 220, 95, 95);
        
        // relleno circulos fila3
        g2d.fillOval(58, 350, 95, 95);
        g2d.fillOval(208, 350, 95, 95);
        g2d.fillOval(358, 350, 95, 95);
        
        // establecer color borde circulos 
        g2d.setColor(Color.black);
        
        // borde circulos fila 1
        g2d.drawOval(58, 90, 95, 95);
        g2d.drawOval(208, 90, 95, 95);
        g2d.drawOval(358, 90, 95, 95);
        
        //borde circulos fila 2 
        g2d.drawOval(58, 220, 95, 95);
        g2d.drawOval(208, 220, 95, 95);
        g2d.drawOval(358, 220, 95, 95);
        
        //borde circulos fila 3
        g2d.drawOval(58, 350, 95, 95);
        g2d.drawOval(208, 350, 95, 95);
        g2d.drawOval(358, 350, 95, 95);
        
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanat2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanat2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanat2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanat2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanat2d().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
